 FROM ubuntu:24.04 AS base

ENV DEBIAN_FRONTEND=noninteractive LANG="C.UTF-8"
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

FROM base AS builder

WORKDIR /

ARG CREDO_VERSION="v0.16.0"
ARG CREDO_ARCH="amd64"
ARG CREDO_URL="https://github.com/CREDOProject/core/releases/download/${CREDO_VERSION}/linux_${CREDO_ARCH}_credo.zip"

RUN set -x \
 && apt-get update -yq --no-install-recommends \
 && apt-get install -yq --no-install-recommends \
    ca-certificates \
    curl \
    unzip \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/* \
 && curl -fsSL --proto '=https' --tlsv1.2 "${CREDO_URL}" -o credo.zip \
 && unzip credo.zip \
 && rm -f credo.zip \
 && chmod +x credo

FROM base AS final

RUN apt-get update && apt-get install -yq --no-install-recommends \
    build-essential \
    r-base \
    gfortran \
    ca-certificates

COPY --from=builder /credo /usr/bin/credo
WORKDIR /workdir

