FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive LANG="C.UTF-8"
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

ARG CREDO_VERSION=v0.16.0
ARG CREDO_ARCH=amd64
ARG CREDO_URL=https://github.com/CREDOProject/core/releases/download/${CREDO_VERSION}/linux_${CREDO_ARCH}_credo.zip

RUN apt-get update -y && apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    unzip \
    build-essential \
    gfortran \
 && rm -rf /var/lib/apt/lists/* \
 && curl -fsSL --proto '=https' --tlsv1.2 "$CREDO_URL" -o credo.zip \
 && unzip credo.zip \
 && mv credo /usr/bin/credo \
 && chmod +x /usr/bin/credo \
 && rm -f credo.zip
