FROM ghcr.io/credoproject/core:v0.17.2-amd64
COPY credo_env /credo_env
RUN apt-get update
WORKDIR /credo_env

RUN credo apply
CMD ["jupyter", "lab", "--ip=0.0.0.0", "--allow-root", "--no-browser", "--NotebookApp.token=''", "--NotebookApp.password=''"]
